### PR TITLE
add uuid support to image creation

### PR DESCRIPTION
**Pull request by eatmyvenom**
Small patch that changes image creation to use uuids instead of name for leaderboard positions

### CODE REVIEW

**Review by Blackoutburst — CHANGES_REQUESTED** [review]
You inverted the if statement `user.length() == 36` should check the uuid but rn it's checking the name
image

**Comment by eatmyvenom** [comment]
# FRICC

**Comment by Blackoutburst** [comment]
I have faith in you, you can do it

**Review by Blackoutburst — APPROVED** [review]
Ok it should work gonna merge rn then merge #32

**Pull request merged**
