### PR TITLE
Remove a bunch of code duplication

### PR DESCRIPTION
**Pull request by eatmyvenom**
A few of the commands had a bit of duplicate code which Codacy flagged as an issue. This adds a new method to GeneralUtils to handle some image generation and adds a new Leaderboard class to handle general use of leaderboards in commands.

### CODE REVIEW

**Comment by eatmyvenom** [comment]
I'm not sure why Codacy is complaining about the imports since I use each class from that package.

**Comment by eatmyvenom** [comment]
Also there is a bugfix in here 
```diff
	public static String getLBPos(String user, char type) {
-		return " (#"+ getLBPosToInt(user, type) + ")";
+		int pos = getLBPosToInt(user, type) + 1;
+		return " (#"+ pos + ")";
	}
```
Before the position was the array index and was not the actual leaderboard position.

**Comment by eatmyvenom** [comment]
Oh yea I forgot to add, I have tested this to make sure all of the changes here work. It works without any errors!

**Review by Blackoutburst — APPROVED** [review]
Applying modification on Wally right now

**Pull request merged**
