### PR TITLE
Make sure player data file exists before reading it.

### PR DESCRIPTION
**Pull request by eatmyvenom**
It appears that its possible for a file to be removed while the tracker thread is looping through the list of players. This PR adds a simple check to make sure the file exists just prior to reading it.

### CODE REVIEW

**Comment by Blackoutburst** [comment]
I think you should just do
`if(!tmpFile.exists()) continue;`
Instead of puting everything inside a condition

**Review by Blackoutburst — CHANGES_REQUESTED** [review]
Nice but i would prefer if you use something like this `if(!tmpFile.exists()) continue;` instead of puting everything inside a big if statement
and this will be more compliant with the rest of the code

**Comment by eatmyvenom** [comment]
I've committed the change and I believe this is ready for merge whenever you are ready.

**Comment by eatmyvenom** [comment]
For future reference I feel like a `CONTRIBUTING.MD` file would be helpful to lay out standards for pull requests.

**Review by Blackoutburst — APPROVED** [review]

**Pull request merged**
